default:
  tags: ["arch:amd64"]
  retry:
    max: 1 # Retry everything once on failure
    when: always

stages:
  - build
  - test
  - package

# Workflow rules
# Rules used to define whether a pipeline should run, and with which variables
#
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "web"

variables:
  GOPATH: $CI_PROJECT_DIR/.go
  GO_VERSION: "1.25.8"
  CI_IMAGE_GBI_JAMMY: registry.ddbuild.io/ci/dd-go:gbi-jammy@sha256:27a9faecce3ef65bf9879a0ae2de80e0791dbd1191213188c46bb77ee9fab78e
  CI_IDENTITIES_VERSION: 0.6.1
  CI_IDENTITIES_URI: s3://binaries-ddbuild-io-prod/ci-identities/ci-identities-gitlab-job-client/versions/v${CI_IDENTITIES_VERSION}/ci-identities-gitlab-job-client-linux-amd64
  PACKAGER_REVISION: main

.go-cache:
  cache:
    key: go-mod-$CI_COMMIT_REF_SLUG-$GO_VERSION
    paths:
      - .go/pkg/mod/
    fallback_keys:
      - go-modules-prod-${GO_VERSION}

build:
  extends: .go-cache
  stage: build
  image: $CI_IMAGE_GBI_JAMMY
  script:
    - make build

test-all:
  extends: .go-cache
  stage: test
  image: $CI_IMAGE_GBI_JAMMY
  before_script:
    - apt-get update -qq && apt-get install -y -qq shellcheck
  script:
    - make ci

package:
  variables:
    VAULT_ADDR: "???????"
    VAULT_TOKEN: "!!!!!!!"
  id_tokens:
    CI_IDENTITIES_GITLAB_ID_TOKEN:
      aud: ci-identities
  stage: package
  image: $CI_IMAGE_GBI_JAMMY
  before_script:
      - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.ddbuild.io/DataDog/".insteadOf "https://github.com/DataDog/"
  script:
    - aws s3 cp ${CI_IDENTITIES_URI} ./ci-identities-gitlab-job-client
    - chmod u+x ./ci-identities-gitlab-job-client
    # - ./ci-identities-gitlab-job-client secrets read "helm-plugin-gpg" "key"
    - go install github.com/DataDog/software-integrity-and-trust/sint-4674-helm-plugin-build-and-release/cmd/cli@${PACKAGER_REVISION}
    - $GOPATH/bin/cli --help
    - $GOPATH/bin/cli export-public-key --vault-key crypto/ci/keys/datadog_helm-plugin_untrusted-jobs_helm-plugin-testing-signing-key --user-id "DataDog, Inc." --user-email "package+helm@datadoghq.com" > public-key.pub
    - PACKAGER=$GOPATH/bin/cli make package-ci
